global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'http://3.38.231.223:80' ] # 실 서버
#      - targets: [ 'host.docker.internal:80' ] # 로컬 테스팅용