#green
version: '3'
services:
  redis:
    image: redis
    ports:
      - "6381:6379"
  backend:
    build: .
    ports:
      - "8082:80"
    container_name: yello-green
    environment:
      - SPRING_PROFILES_ACTIVE=green
    depends_on:
      - redis
