#blue
version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  backend:
    build: .
    ports:
      - "8081:80"
    container_name: yello-blue
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=blue
    depends_on:
      - redis
